patches:
  - name: myapp-dev
    labels:
      app: myapp-dev
    resources:
      # deployment
      - target:
          kind: Deployment
          name: myapp
        patches:
          - op: replace
            path: /spec/replicas
            value: 1

          - op: replace
            path: /spec/template/spec/containers/0/image
            value: "localhost:5000/restapiapp:1.22"

          - op: add
            path: /spec/template/spec/containers/0/env
            value:
              - name: RESTAPIAPP_VERSION
                value: dev
              - name: LOG_LEVEL
                value: debug

      # service
      - target:
          kind: Service
          name: myapp
        patches:
          - op: add
            path: /spec/ports/0/nodePort
            value: 30265
