kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
  - |
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
      endpoint = ["http://kind-registry:5000"]
name: "kubepatch"
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30000
        hostPort: 30000
      # app-dev
      - containerPort: 30265
        hostPort: 30265
        protocol: TCP
      # app-prod
      - containerPort: 30266
        hostPort: 30266
        protocol: TCP
      # postgres
      - containerPort: 30267
        hostPort: 30267
        protocol: TCP
      # keycloak
      - containerPort: 30268
        hostPort: 30268
        protocol: TCP
