apiVersion: v1
kind: Namespace
metadata:
  name: kassert-test
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-config
  namespace: kassert-test
data:
  APP_ENV: "production"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  namespace: kassert-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
        - name: nginx
          image: nginx:1.21
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: example-service
  namespace: kassert-test
spec:
  selector:
    app: example
  ports:
    - port: 80
  type: ClusterIP
