---
apiVersion: v1
kind: Service
metadata:
  name: &app postgresql
  labels:
    app: *app
spec:
  type: NodePort
  selector:
    app: *app
  ports:
    - port: 5432

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-conf
data:
  postgresql.conf: |
    listen_addresses                = '*'
    port                            = 5432
    max_connections                 = 250
    superuser_reserved_connections  = 3
    log_lock_waits                  = on
    log_temp_files                  = 0
    log_checkpoints                 = on
    log_connections                 = off
    log_destination                 = 'stderr'
    log_error_verbosity             = 'DEFAULT'
    log_min_messages                = 'WARNING'
    log_hostname                    = off
    log_timezone                    = 'Asia/Aqtau'
    log_line_prefix                 = '%t [%p-%l] %r %q%u@%d '
    datestyle                       = 'iso, mdy'
    timezone                        = 'Asia/Aqtau'

---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql
stringData: { }

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: &app postgresql
  labels:
    app: *app
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 32Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: &app postgresql
  labels:
    app: *app
spec:
  replicas: 1
  serviceName: *app
  selector:
    matchLabels:
      app: *app
  template:
    metadata:
      labels:
        app: *app
    spec:
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: *app
        - name: dshm
          emptyDir:
            medium: Memory
        - name: postgresql-conf
          configMap:
            name: postgresql-conf
      containers:
        - name: *app
          image: "postgres:17.5-bookworm"
          imagePullPolicy: Always
          terminationMessagePolicy: FallbackToLogsOnError
          args:
            - -c
            - config_file=/etc/postgresql/postgresql.conf
          env:
            - name: TZ
              value: Asia/Aqtau
            - name: POSTGRES_INITDB_ARGS
              value: "--encoding=UTF-8 --lc-collate=ru_RU.UTF-8 --lc-ctype=ru_RU.UTF-8"
          envFrom:
            - secretRef:
                name: *app
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
            requests:
              cpu: 128m
              memory: 256Mi
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: storage
            - mountPath: /dev/shm
              name: dshm
            - mountPath: /etc/postgresql
              name: postgresql-conf
