---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak
stringData: {}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak
data: {}

---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: &app keycloak
spec:
  replicas: 1
  serviceName: *app
  template:
    spec:
      initContainers:
        - name: wait-db
          image: "busybox:latest"
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -euc
            - |
              while ! nc -z postgresql 5432; do
                echo "Waiting for Postgres to boot";
                sleep 1;
              done;
              echo "Postgres is ready";
      containers:
        - name: *app
          image: "quay.io/keycloak/keycloak:26.1.2"
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: FallbackToLogsOnError
          args: ["start"]
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - secretRef:
                name: *app
            - configMapRef:
                name: *app
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 128m
              memory: 512Mi
